#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 92
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 12
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_let = 2,
  anon_sym_EQ = 3,
  anon_sym_LPAREN = 4,
  anon_sym_COLON = 5,
  anon_sym_COMMA = 6,
  anon_sym_RPAREN = 7,
  anon_sym_DASH_GT = 8,
  sym_ident = 9,
  anon_sym_LBRACK = 10,
  anon_sym_RBRACK = 11,
  anon_sym_LBRACE = 12,
  anon_sym_RBRACE = 13,
  anon_sym_if = 14,
  anon_sym_else = 15,
  sym_number = 16,
  sym_string = 17,
  anon_sym_LT = 18,
  anon_sym_GT = 19,
  anon_sym_PLUS = 20,
  anon_sym_DASH = 21,
  anon_sym_PERCENT = 22,
  anon_sym_EQ_EQ = 23,
  anon_sym_return = 24,
  anon_sym_do = 25,
  anon_sym_break = 26,
  anon_sym_loop = 27,
  sym_source_file = 28,
  sym_func = 29,
  sym_type = 30,
  sym_body = 31,
  sym_stmt = 32,
  sym_if_stmt = 33,
  sym_expr = 34,
  sym_binary_expr = 35,
  sym_binary_op = 36,
  sym_return_stmt = 37,
  sym_do_stmt = 38,
  sym_break_stmt = 39,
  sym_loop_stmt = 40,
  sym_func_call = 41,
  sym_var_decl_stmt = 42,
  sym_var_assign_stmt = 43,
  sym_array_index = 44,
  aux_sym_source_file_repeat1 = 45,
  aux_sym_func_repeat1 = 46,
  aux_sym_body_repeat1 = 47,
  aux_sym_if_stmt_repeat1 = 48,
  aux_sym_func_call_repeat1 = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH_GT] = "->",
  [sym_ident] = "ident",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [sym_number] = "number",
  [sym_string] = "string",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_PERCENT] = "%",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_return] = "return",
  [anon_sym_do] = "do",
  [anon_sym_break] = "break",
  [anon_sym_loop] = "loop",
  [sym_source_file] = "source_file",
  [sym_func] = "func",
  [sym_type] = "type",
  [sym_body] = "body",
  [sym_stmt] = "stmt",
  [sym_if_stmt] = "if_stmt",
  [sym_expr] = "expr",
  [sym_binary_expr] = "binary_expr",
  [sym_binary_op] = "binary_op",
  [sym_return_stmt] = "return_stmt",
  [sym_do_stmt] = "do_stmt",
  [sym_break_stmt] = "break_stmt",
  [sym_loop_stmt] = "loop_stmt",
  [sym_func_call] = "func_call",
  [sym_var_decl_stmt] = "var_decl_stmt",
  [sym_var_assign_stmt] = "var_assign_stmt",
  [sym_array_index] = "array_index",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_func_repeat1] = "func_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
  [aux_sym_if_stmt_repeat1] = "if_stmt_repeat1",
  [aux_sym_func_call_repeat1] = "func_call_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [sym_ident] = sym_ident,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_do] = anon_sym_do,
  [anon_sym_break] = anon_sym_break,
  [anon_sym_loop] = anon_sym_loop,
  [sym_source_file] = sym_source_file,
  [sym_func] = sym_func,
  [sym_type] = sym_type,
  [sym_body] = sym_body,
  [sym_stmt] = sym_stmt,
  [sym_if_stmt] = sym_if_stmt,
  [sym_expr] = sym_expr,
  [sym_binary_expr] = sym_binary_expr,
  [sym_binary_op] = sym_binary_op,
  [sym_return_stmt] = sym_return_stmt,
  [sym_do_stmt] = sym_do_stmt,
  [sym_break_stmt] = sym_break_stmt,
  [sym_loop_stmt] = sym_loop_stmt,
  [sym_func_call] = sym_func_call,
  [sym_var_decl_stmt] = sym_var_decl_stmt,
  [sym_var_assign_stmt] = sym_var_assign_stmt,
  [sym_array_index] = sym_array_index,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_func_repeat1] = aux_sym_func_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
  [aux_sym_if_stmt_repeat1] = aux_sym_if_stmt_repeat1,
  [aux_sym_func_call_repeat1] = aux_sym_func_call_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_break] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_loop] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_func] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_if_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_op] = {
    .visible = true,
    .named = true,
  },
  [sym_return_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_do_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_break_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_loop_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_func_call] = {
    .visible = true,
    .named = true,
  },
  [sym_var_decl_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_var_assign_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_array_index] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_func_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_if_stmt_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_func_call_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 5,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 9,
  [12] = 12,
  [13] = 13,
  [14] = 5,
  [15] = 9,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 27,
  [35] = 29,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 29,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 27,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '"', 2,
        '#', 12,
        '%', 56,
        '(', 17,
        ')', 20,
        '+', 53,
        ',', 19,
        '-', 55,
        '0', 48,
        ':', 18,
        '<', 51,
        '=', 16,
        '>', 52,
        '[', 41,
        ']', 42,
        'b', 35,
        'd', 31,
        'e', 29,
        'i', 27,
        'l', 23,
        'r', 26,
        '{', 43,
        '}', 44,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(49);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 2,
        '#', 12,
        ')', 20,
        ',', 19,
        '-', 6,
        '0', 48,
        '=', 15,
        '[', 41,
        '{', 43,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(49);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '#', 12,
        '%', 56,
        '(', 17,
        ')', 20,
        '+', 53,
        ',', 19,
        '-', 54,
        '<', 51,
        '=', 5,
        '>', 52,
        '[', 41,
        ']', 42,
        'b', 35,
        'd', 31,
        'i', 27,
        'l', 23,
        'r', 26,
        '{', 43,
        '}', 44,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '#', 12,
        '%', 56,
        ')', 20,
        '+', 53,
        ',', 19,
        '-', 54,
        '<', 51,
        '=', 16,
        '>', 52,
        ']', 42,
        'b', 35,
        'd', 31,
        'i', 27,
        'l', 23,
        'r', 26,
        '{', 43,
        '}', 44,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(57);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(21);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == 'f') ADVANCE(45);
      END_STATE();
    case 9:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '#', 12,
        '%', 56,
        ')', 20,
        '+', 53,
        ',', 19,
        '-', 54,
        '<', 51,
        '=', 5,
        '>', 52,
        ']', 42,
        'i', 8,
        'l', 7,
        '{', 43,
      );
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(57);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'a') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(37);
      if (lookahead == 'o') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'f') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'k') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'l') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'n') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'o') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'o') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'p') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'r') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'r') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 's') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 't') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 't') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'u') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_else);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_number);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(21);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_do);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_break);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_loop);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 10},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 10},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 10},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 10},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 10},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 10},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 10},
  [49] = {.lex_state = 10},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 10},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 10},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 10},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 10},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 10},
  [74] = {.lex_state = 10},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
    [anon_sym_break] = ACTIONS(1),
    [anon_sym_loop] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(85),
    [sym_func] = STATE(48),
    [aux_sym_source_file_repeat1] = STATE(48),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_let] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 7,
      anon_sym_let,
      sym_ident,
      anon_sym_if,
      anon_sym_return,
      anon_sym_do,
      anon_sym_break,
      anon_sym_loop,
    ACTIONS(13), 11,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
  [32] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 8,
      anon_sym_let,
      anon_sym_EQ,
      sym_ident,
      anon_sym_if,
      anon_sym_return,
      anon_sym_do,
      anon_sym_break,
      anon_sym_loop,
    ACTIONS(19), 11,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
  [59] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(46), 1,
      sym_binary_op,
    ACTIONS(21), 7,
      anon_sym_let,
      sym_ident,
      anon_sym_if,
      anon_sym_return,
      anon_sym_do,
      anon_sym_break,
      anon_sym_loop,
    ACTIONS(23), 11,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
  [88] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_let,
    ACTIONS(27), 1,
      sym_ident,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_return,
    ACTIONS(35), 1,
      anon_sym_do,
    ACTIONS(37), 1,
      anon_sym_break,
    ACTIONS(39), 1,
      anon_sym_loop,
    STATE(87), 1,
      sym_array_index,
    STATE(8), 2,
      sym_stmt,
      aux_sym_body_repeat1,
    STATE(31), 7,
      sym_if_stmt,
      sym_return_stmt,
      sym_do_stmt,
      sym_break_stmt,
      sym_loop_stmt,
      sym_var_decl_stmt,
      sym_var_assign_stmt,
  [132] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_let,
    ACTIONS(27), 1,
      sym_ident,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_return,
    ACTIONS(35), 1,
      anon_sym_do,
    ACTIONS(37), 1,
      anon_sym_break,
    ACTIONS(39), 1,
      anon_sym_loop,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    STATE(87), 1,
      sym_array_index,
    STATE(8), 2,
      sym_stmt,
      aux_sym_body_repeat1,
    STATE(31), 7,
      sym_if_stmt,
      sym_return_stmt,
      sym_do_stmt,
      sym_break_stmt,
      sym_loop_stmt,
      sym_var_decl_stmt,
      sym_var_assign_stmt,
  [176] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 7,
      anon_sym_let,
      sym_ident,
      anon_sym_if,
      anon_sym_return,
      anon_sym_do,
      anon_sym_break,
      anon_sym_loop,
    ACTIONS(13), 11,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
  [202] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_let,
    ACTIONS(46), 1,
      sym_ident,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    ACTIONS(51), 1,
      anon_sym_if,
    ACTIONS(54), 1,
      anon_sym_return,
    ACTIONS(57), 1,
      anon_sym_do,
    ACTIONS(60), 1,
      anon_sym_break,
    ACTIONS(63), 1,
      anon_sym_loop,
    STATE(87), 1,
      sym_array_index,
    STATE(8), 2,
      sym_stmt,
      aux_sym_body_repeat1,
    STATE(31), 7,
      sym_if_stmt,
      sym_return_stmt,
      sym_do_stmt,
      sym_break_stmt,
      sym_loop_stmt,
      sym_var_decl_stmt,
      sym_var_assign_stmt,
  [246] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_let,
    ACTIONS(27), 1,
      sym_ident,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_return,
    ACTIONS(35), 1,
      anon_sym_do,
    ACTIONS(37), 1,
      anon_sym_break,
    ACTIONS(39), 1,
      anon_sym_loop,
    ACTIONS(66), 1,
      anon_sym_RBRACE,
    STATE(87), 1,
      sym_array_index,
    STATE(6), 2,
      sym_stmt,
      aux_sym_body_repeat1,
    STATE(31), 7,
      sym_if_stmt,
      sym_return_stmt,
      sym_do_stmt,
      sym_break_stmt,
      sym_loop_stmt,
      sym_var_decl_stmt,
      sym_var_assign_stmt,
  [290] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 7,
      anon_sym_let,
      sym_ident,
      anon_sym_if,
      anon_sym_return,
      anon_sym_do,
      anon_sym_break,
      anon_sym_loop,
    ACTIONS(70), 11,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
  [316] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_let,
    ACTIONS(27), 1,
      sym_ident,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_return,
    ACTIONS(35), 1,
      anon_sym_do,
    ACTIONS(37), 1,
      anon_sym_break,
    ACTIONS(39), 1,
      anon_sym_loop,
    ACTIONS(72), 1,
      anon_sym_RBRACE,
    STATE(87), 1,
      sym_array_index,
    STATE(14), 2,
      sym_stmt,
      aux_sym_body_repeat1,
    STATE(31), 7,
      sym_if_stmt,
      sym_return_stmt,
      sym_do_stmt,
      sym_break_stmt,
      sym_loop_stmt,
      sym_var_decl_stmt,
      sym_var_assign_stmt,
  [360] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 7,
      anon_sym_let,
      sym_ident,
      anon_sym_if,
      anon_sym_return,
      anon_sym_do,
      anon_sym_break,
      anon_sym_loop,
    ACTIONS(76), 11,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
  [386] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 7,
      anon_sym_let,
      sym_ident,
      anon_sym_if,
      anon_sym_return,
      anon_sym_do,
      anon_sym_break,
      anon_sym_loop,
    ACTIONS(80), 11,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
  [412] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_let,
    ACTIONS(27), 1,
      sym_ident,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_return,
    ACTIONS(35), 1,
      anon_sym_do,
    ACTIONS(37), 1,
      anon_sym_break,
    ACTIONS(39), 1,
      anon_sym_loop,
    ACTIONS(82), 1,
      anon_sym_RBRACE,
    STATE(87), 1,
      sym_array_index,
    STATE(8), 2,
      sym_stmt,
      aux_sym_body_repeat1,
    STATE(31), 7,
      sym_if_stmt,
      sym_return_stmt,
      sym_do_stmt,
      sym_break_stmt,
      sym_loop_stmt,
      sym_var_decl_stmt,
      sym_var_assign_stmt,
  [456] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_let,
    ACTIONS(27), 1,
      sym_ident,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_return,
    ACTIONS(35), 1,
      anon_sym_do,
    ACTIONS(37), 1,
      anon_sym_break,
    ACTIONS(39), 1,
      anon_sym_loop,
    ACTIONS(84), 1,
      anon_sym_RBRACE,
    STATE(87), 1,
      sym_array_index,
    STATE(5), 2,
      sym_stmt,
      aux_sym_body_repeat1,
    STATE(31), 7,
      sym_if_stmt,
      sym_return_stmt,
      sym_do_stmt,
      sym_break_stmt,
      sym_loop_stmt,
      sym_var_decl_stmt,
      sym_var_assign_stmt,
  [500] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_RBRACE,
    STATE(46), 1,
      sym_binary_op,
    ACTIONS(90), 6,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
    ACTIONS(86), 7,
      anon_sym_let,
      sym_ident,
      anon_sym_if,
      anon_sym_return,
      anon_sym_do,
      anon_sym_break,
      anon_sym_loop,
  [527] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_RBRACE,
    STATE(46), 1,
      sym_binary_op,
    ACTIONS(90), 6,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
    ACTIONS(92), 7,
      anon_sym_let,
      sym_ident,
      anon_sym_if,
      anon_sym_return,
      anon_sym_do,
      anon_sym_break,
      anon_sym_loop,
  [554] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_RBRACE,
    STATE(46), 1,
      sym_binary_op,
    ACTIONS(90), 6,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
    ACTIONS(96), 7,
      anon_sym_let,
      sym_ident,
      anon_sym_if,
      anon_sym_return,
      anon_sym_do,
      anon_sym_break,
      anon_sym_loop,
  [581] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_RBRACE,
    STATE(46), 1,
      sym_binary_op,
    ACTIONS(90), 6,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
    ACTIONS(100), 7,
      anon_sym_let,
      sym_ident,
      anon_sym_if,
      anon_sym_return,
      anon_sym_do,
      anon_sym_break,
      anon_sym_loop,
  [608] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    ACTIONS(108), 1,
      anon_sym_else,
    STATE(22), 1,
      aux_sym_if_stmt_repeat1,
    ACTIONS(104), 7,
      anon_sym_let,
      sym_ident,
      anon_sym_if,
      anon_sym_return,
      anon_sym_do,
      anon_sym_break,
      anon_sym_loop,
  [630] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      anon_sym_COMMA,
    ACTIONS(112), 1,
      anon_sym_RPAREN,
    STATE(46), 1,
      sym_binary_op,
    STATE(54), 1,
      aux_sym_func_call_repeat1,
    ACTIONS(90), 6,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
  [654] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_else,
    ACTIONS(116), 1,
      anon_sym_RBRACE,
    STATE(23), 1,
      aux_sym_if_stmt_repeat1,
    ACTIONS(114), 7,
      anon_sym_let,
      sym_ident,
      anon_sym_if,
      anon_sym_return,
      anon_sym_do,
      anon_sym_break,
      anon_sym_loop,
  [676] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 1,
      anon_sym_RBRACE,
    ACTIONS(122), 1,
      anon_sym_else,
    STATE(23), 1,
      aux_sym_if_stmt_repeat1,
    ACTIONS(118), 7,
      anon_sym_let,
      sym_ident,
      anon_sym_if,
      anon_sym_return,
      anon_sym_do,
      anon_sym_break,
      anon_sym_loop,
  [698] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_RBRACE,
    ACTIONS(125), 8,
      anon_sym_let,
      sym_ident,
      anon_sym_if,
      anon_sym_else,
      anon_sym_return,
      anon_sym_do,
      anon_sym_break,
      anon_sym_loop,
  [715] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 1,
      anon_sym_RBRACE,
    ACTIONS(118), 8,
      anon_sym_let,
      sym_ident,
      anon_sym_if,
      anon_sym_else,
      anon_sym_return,
      anon_sym_do,
      anon_sym_break,
      anon_sym_loop,
  [732] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(46), 1,
      sym_binary_op,
    ACTIONS(129), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(90), 6,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
  [751] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_RBRACE,
    ACTIONS(131), 8,
      anon_sym_let,
      sym_ident,
      anon_sym_if,
      anon_sym_else,
      anon_sym_return,
      anon_sym_do,
      anon_sym_break,
      anon_sym_loop,
  [768] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_LBRACE,
    STATE(24), 1,
      sym_body,
    STATE(46), 1,
      sym_binary_op,
    ACTIONS(90), 6,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
  [789] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_RBRACE,
    ACTIONS(137), 8,
      anon_sym_let,
      sym_ident,
      anon_sym_if,
      anon_sym_else,
      anon_sym_return,
      anon_sym_do,
      anon_sym_break,
      anon_sym_loop,
  [806] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_LBRACE,
    STATE(20), 1,
      sym_body,
    STATE(46), 1,
      sym_binary_op,
    ACTIONS(90), 6,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
  [827] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_RBRACE,
    ACTIONS(141), 7,
      anon_sym_let,
      sym_ident,
      anon_sym_if,
      anon_sym_return,
      anon_sym_do,
      anon_sym_break,
      anon_sym_loop,
  [843] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_RBRACE,
    ACTIONS(145), 7,
      anon_sym_let,
      sym_ident,
      anon_sym_if,
      anon_sym_return,
      anon_sym_do,
      anon_sym_break,
      anon_sym_loop,
  [859] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_RBRACK,
    STATE(46), 1,
      sym_binary_op,
    ACTIONS(90), 6,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
  [877] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_RBRACE,
    ACTIONS(131), 7,
      anon_sym_let,
      sym_ident,
      anon_sym_if,
      anon_sym_return,
      anon_sym_do,
      anon_sym_break,
      anon_sym_loop,
  [893] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_RBRACE,
    ACTIONS(137), 7,
      anon_sym_let,
      sym_ident,
      anon_sym_if,
      anon_sym_return,
      anon_sym_do,
      anon_sym_break,
      anon_sym_loop,
  [909] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_RPAREN,
    ACTIONS(153), 1,
      sym_ident,
    STATE(21), 1,
      sym_expr,
    ACTIONS(155), 2,
      sym_number,
      sym_string,
    STATE(7), 3,
      sym_binary_expr,
      sym_func_call,
      sym_array_index,
  [931] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_RBRACE,
    ACTIONS(157), 7,
      anon_sym_let,
      sym_ident,
      anon_sym_if,
      anon_sym_return,
      anon_sym_do,
      anon_sym_break,
      anon_sym_loop,
  [947] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      sym_ident,
    STATE(16), 1,
      sym_expr,
    ACTIONS(155), 2,
      sym_number,
      sym_string,
    STATE(7), 3,
      sym_binary_expr,
      sym_func_call,
      sym_array_index,
  [966] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      sym_ident,
    STATE(18), 1,
      sym_expr,
    ACTIONS(155), 2,
      sym_number,
      sym_string,
    STATE(7), 3,
      sym_binary_expr,
      sym_func_call,
      sym_array_index,
  [985] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      sym_ident,
    STATE(26), 1,
      sym_expr,
    ACTIONS(155), 2,
      sym_number,
      sym_string,
    STATE(7), 3,
      sym_binary_expr,
      sym_func_call,
      sym_array_index,
  [1004] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      sym_ident,
    STATE(17), 1,
      sym_expr,
    ACTIONS(155), 2,
      sym_number,
      sym_string,
    STATE(7), 3,
      sym_binary_expr,
      sym_func_call,
      sym_array_index,
  [1023] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      sym_ident,
    STATE(28), 1,
      sym_expr,
    ACTIONS(155), 2,
      sym_number,
      sym_string,
    STATE(7), 3,
      sym_binary_expr,
      sym_func_call,
      sym_array_index,
  [1042] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      sym_ident,
    STATE(19), 1,
      sym_expr,
    ACTIONS(155), 2,
      sym_number,
      sym_string,
    STATE(7), 3,
      sym_binary_expr,
      sym_func_call,
      sym_array_index,
  [1061] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      sym_ident,
    STATE(33), 1,
      sym_expr,
    ACTIONS(155), 2,
      sym_number,
      sym_string,
    STATE(7), 3,
      sym_binary_expr,
      sym_func_call,
      sym_array_index,
  [1080] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      sym_ident,
    STATE(30), 1,
      sym_expr,
    ACTIONS(155), 2,
      sym_number,
      sym_string,
    STATE(7), 3,
      sym_binary_expr,
      sym_func_call,
      sym_array_index,
  [1099] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      sym_ident,
    STATE(4), 1,
      sym_expr,
    ACTIONS(155), 2,
      sym_number,
      sym_string,
    STATE(7), 3,
      sym_binary_expr,
      sym_func_call,
      sym_array_index,
  [1118] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_LBRACK,
    ACTIONS(161), 4,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
  [1131] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(165), 1,
      ts_builtin_sym_end,
    STATE(49), 2,
      sym_func,
      aux_sym_source_file_repeat1,
  [1145] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      ts_builtin_sym_end,
    ACTIONS(169), 1,
      anon_sym_let,
    STATE(49), 2,
      sym_func,
      aux_sym_source_file_repeat1,
  [1159] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 4,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
  [1169] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 3,
      sym_ident,
      sym_number,
      sym_string,
  [1178] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_COMMA,
    ACTIONS(178), 1,
      anon_sym_RPAREN,
    STATE(56), 1,
      aux_sym_func_repeat1,
  [1191] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_LBRACE,
    ACTIONS(180), 1,
      anon_sym_if,
    STATE(25), 1,
      sym_body,
  [1204] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      anon_sym_COMMA,
    ACTIONS(182), 1,
      anon_sym_RPAREN,
    STATE(57), 1,
      aux_sym_func_call_repeat1,
  [1217] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_COMMA,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
    STATE(55), 1,
      aux_sym_func_repeat1,
  [1230] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_COMMA,
    ACTIONS(189), 1,
      anon_sym_RPAREN,
    STATE(55), 1,
      aux_sym_func_repeat1,
  [1243] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_RPAREN,
    ACTIONS(191), 1,
      anon_sym_COMMA,
    STATE(57), 1,
      aux_sym_func_call_repeat1,
  [1256] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      anon_sym_RPAREN,
    ACTIONS(196), 1,
      sym_ident,
  [1266] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1274] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 2,
      ts_builtin_sym_end,
      anon_sym_let,
  [1282] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      anon_sym_LBRACE,
    STATE(64), 1,
      sym_body,
  [1292] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 2,
      ts_builtin_sym_end,
      anon_sym_let,
  [1300] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      sym_ident,
    STATE(84), 1,
      sym_type,
  [1310] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 2,
      ts_builtin_sym_end,
      anon_sym_let,
  [1318] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_LBRACE,
    STATE(32), 1,
      sym_body,
  [1328] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      anon_sym_LBRACE,
    STATE(60), 1,
      sym_body,
  [1338] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      sym_ident,
    STATE(66), 1,
      sym_type,
  [1348] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      sym_ident,
    STATE(61), 1,
      sym_type,
  [1358] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      sym_ident,
    STATE(71), 1,
      sym_type,
  [1368] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      sym_ident,
    STATE(52), 1,
      sym_type,
  [1378] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      anon_sym_LBRACE,
    STATE(73), 1,
      sym_body,
  [1388] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(210), 1,
      anon_sym_EQ,
  [1398] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 2,
      ts_builtin_sym_end,
      anon_sym_let,
  [1406] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 2,
      ts_builtin_sym_end,
      anon_sym_let,
  [1414] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      sym_ident,
    STATE(59), 1,
      sym_type,
  [1424] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_COLON,
  [1431] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_LPAREN,
  [1438] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 1,
      anon_sym_DASH_GT,
  [1445] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_RBRACK,
  [1452] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      sym_ident,
  [1459] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      sym_ident,
  [1466] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_COLON,
  [1473] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      anon_sym_EQ,
  [1480] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_EQ,
  [1487] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      ts_builtin_sym_end,
  [1494] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_DASH_GT,
  [1501] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_EQ,
  [1508] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      sym_number,
  [1515] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      sym_ident,
  [1522] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      anon_sym_DASH_GT,
  [1529] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 32,
  [SMALL_STATE(4)] = 59,
  [SMALL_STATE(5)] = 88,
  [SMALL_STATE(6)] = 132,
  [SMALL_STATE(7)] = 176,
  [SMALL_STATE(8)] = 202,
  [SMALL_STATE(9)] = 246,
  [SMALL_STATE(10)] = 290,
  [SMALL_STATE(11)] = 316,
  [SMALL_STATE(12)] = 360,
  [SMALL_STATE(13)] = 386,
  [SMALL_STATE(14)] = 412,
  [SMALL_STATE(15)] = 456,
  [SMALL_STATE(16)] = 500,
  [SMALL_STATE(17)] = 527,
  [SMALL_STATE(18)] = 554,
  [SMALL_STATE(19)] = 581,
  [SMALL_STATE(20)] = 608,
  [SMALL_STATE(21)] = 630,
  [SMALL_STATE(22)] = 654,
  [SMALL_STATE(23)] = 676,
  [SMALL_STATE(24)] = 698,
  [SMALL_STATE(25)] = 715,
  [SMALL_STATE(26)] = 732,
  [SMALL_STATE(27)] = 751,
  [SMALL_STATE(28)] = 768,
  [SMALL_STATE(29)] = 789,
  [SMALL_STATE(30)] = 806,
  [SMALL_STATE(31)] = 827,
  [SMALL_STATE(32)] = 843,
  [SMALL_STATE(33)] = 859,
  [SMALL_STATE(34)] = 877,
  [SMALL_STATE(35)] = 893,
  [SMALL_STATE(36)] = 909,
  [SMALL_STATE(37)] = 931,
  [SMALL_STATE(38)] = 947,
  [SMALL_STATE(39)] = 966,
  [SMALL_STATE(40)] = 985,
  [SMALL_STATE(41)] = 1004,
  [SMALL_STATE(42)] = 1023,
  [SMALL_STATE(43)] = 1042,
  [SMALL_STATE(44)] = 1061,
  [SMALL_STATE(45)] = 1080,
  [SMALL_STATE(46)] = 1099,
  [SMALL_STATE(47)] = 1118,
  [SMALL_STATE(48)] = 1131,
  [SMALL_STATE(49)] = 1145,
  [SMALL_STATE(50)] = 1159,
  [SMALL_STATE(51)] = 1169,
  [SMALL_STATE(52)] = 1178,
  [SMALL_STATE(53)] = 1191,
  [SMALL_STATE(54)] = 1204,
  [SMALL_STATE(55)] = 1217,
  [SMALL_STATE(56)] = 1230,
  [SMALL_STATE(57)] = 1243,
  [SMALL_STATE(58)] = 1256,
  [SMALL_STATE(59)] = 1266,
  [SMALL_STATE(60)] = 1274,
  [SMALL_STATE(61)] = 1282,
  [SMALL_STATE(62)] = 1292,
  [SMALL_STATE(63)] = 1300,
  [SMALL_STATE(64)] = 1310,
  [SMALL_STATE(65)] = 1318,
  [SMALL_STATE(66)] = 1328,
  [SMALL_STATE(67)] = 1338,
  [SMALL_STATE(68)] = 1348,
  [SMALL_STATE(69)] = 1358,
  [SMALL_STATE(70)] = 1368,
  [SMALL_STATE(71)] = 1378,
  [SMALL_STATE(72)] = 1388,
  [SMALL_STATE(73)] = 1398,
  [SMALL_STATE(74)] = 1406,
  [SMALL_STATE(75)] = 1414,
  [SMALL_STATE(76)] = 1424,
  [SMALL_STATE(77)] = 1431,
  [SMALL_STATE(78)] = 1438,
  [SMALL_STATE(79)] = 1445,
  [SMALL_STATE(80)] = 1452,
  [SMALL_STATE(81)] = 1459,
  [SMALL_STATE(82)] = 1466,
  [SMALL_STATE(83)] = 1473,
  [SMALL_STATE(84)] = 1480,
  [SMALL_STATE(85)] = 1487,
  [SMALL_STATE(86)] = 1494,
  [SMALL_STATE(87)] = 1501,
  [SMALL_STATE(88)] = 1508,
  [SMALL_STATE(89)] = 1515,
  [SMALL_STATE(90)] = 1522,
  [SMALL_STATE(91)] = 1529,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [9] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_index, 4, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_index, 4, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expr, 3, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expr, 3, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func_call, 3, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_call, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func_call, 4, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_call, 4, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func_call, 5, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_call, 5, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_stmt, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_stmt, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_assign_stmt, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_assign_stmt, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_do_stmt, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_do_stmt, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_decl_stmt, 6, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_decl_stmt, 6, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_stmt, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_stmt, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_stmt, 4, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_stmt, 4, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_if_stmt_repeat1, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_if_stmt_repeat1, 2, 0, 0),
  [122] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_if_stmt_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_if_stmt_repeat1, 4, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_if_stmt_repeat1, 4, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_func_call_repeat1, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stmt, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stmt, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_loop_stmt, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loop_stmt, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_break_stmt, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_break_stmt, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 4, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_op, 1, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [184] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_func_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_func_repeat1, 2, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [191] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_func_call_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_func_repeat1, 4, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 11, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 12, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 8, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [232] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lucid(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
